// nextjs-auth-pages/src/pages/forgot-password.tsx
import { GetServerSideProps, InferGetServerSidePropsType } from "next";
import Link from "next/link";

import { auth } from "@/edgedb";
import { BackIcon } from "@/components/icons";

import { SendResetEmailForm } from "@/components/auth";

export const getServerSideProps = (async ({ req }) => {
  return {
    props: { providerInfo: await auth.getProvidersInfo() },
  };
}) satisfies GetServerSideProps<{
  providerInfo: any;
}>;

export default function ForgotPasswordPage({
  providerInfo,
}: InferGetServerSidePropsType<typeof getServerSideProps>) {
  return (
    <main className="my-auto p-8 min-w-[32rem]">
      <Link
        href={"/"}
        className="text-slate-600 inline-flex gap-1 items-center mb-2"
      >
        <BackIcon />
        Home
      </Link>
      <h1 className="text-3xl font-semibold mb-6">Email+Password</h1>

      <div className="flex gap-[5rem] w-max">
        <div className="flex flex-col gap-4">
          <h2 className="text-xl font-semibold">Send password reset email</h2>
          {providerInfo.emailPassword ? (
            <SendResetEmailForm />
          ) : (
            <div className="text-slate-500 italic w-[14rem]">
              Email+Password provider is not enabled
            </div>
          )}
        </div>
      </div>
    </main>
  );
}

// sveltekit-auth/src/routes/forgot-password/+page.svelte
<script>
  import Icon from "@iconify/svelte";
  import ForgotPasswordForm from "$lib/components/auth/ForgotPasswordForm.svelte";

  export let data;
  export let form;
</script>

<div class="p-8 min-w-[32rem]">
  <a href={"/"} class="text-slate-600 inline-flex gap-1 items-center mb-2">
    <Icon icon="mdi:keyboard-backspace" />
    Home
  </a>
  <h1 class="text-3xl font-semibold mb-6">Email+Password</h1>

  <div class="flex gap-[5rem] w-max">
    <div class="flex flex-col gap-4">
      <h2 class="text-xl font-semibold">Send password reset email</h2>
      {#if data.providers.emailPassword}
        <ForgotPasswordForm
          error={form?.error || null}
          message={form?.message || null}
        />
      {:else}
        <div class="text-slate-500 italic w-[14rem]">
          Email+Password provider is not enabled
        </div>
      {/if}
    </div>
  </div>
</div>
