// remix-auth/app/routes/signup.tsx
import {
  useLoaderData,
  Link,
  useSearchParams,
  useActionData,
} from "@remix-run/react";
import { json, redirect } from "@remix-run/node";
import { auth } from "~/services/auth.server";
import { BackIcon } from "../icons";
import SignupForm from "../components/auth/SignupForm";
import { type ActionFunctionArgs } from "@remix-run/node";
import { transformSearchParams } from "~/utils";
import ResendVerificationEmail from "~/components/auth/ResendVerificationEmail";

export const loader = async () => {
  const providerInfo = await auth.getProvidersInfo();

  return json({
    providerInfo,
  });
};

export default function SignUpPage() {
  const { providerInfo } = useLoaderData<typeof loader>();
  const data = useActionData<typeof action>();

  const [searchParams] = useSearchParams();
  const params = transformSearchParams(searchParams);

  return (
    <main className="h-screen flex justify-center items-center">
      <div className="p-8 min-w-[32rem]">
        <Link
          to={"/"}
          className="text-slate-600 inline-flex gap-1 items-center mb-2"
        >
          <BackIcon />
          Home
        </Link>
        <h1 className="text-3xl font-semibold mb-6">Sign up</h1>

        <div className="flex gap-[5rem] w-max">
          <div className="flex flex-col gap-4">
            <h2 className="text-xl font-semibold">Email+Password</h2>

            {params.email_verification_error ? (
              <div className="bg-rose-100 text-rose-950 px-4 py-3 rounded-md w-[22rem] flex flex-col items-start">
                {params.email_verification_error}
                {params.verification_token ? (
                  <ResendVerificationEmail
                    verificationToken={
                      Array.isArray(params.verification_token)
                        ? params.verification_token[0]
                        : params.verification_token
                    }
                  />
                ) : null}
              </div>
            ) : null}

            {providerInfo.emailPassword ? (
              <SignupForm error={data?.error} message={data?.message} />
            ) : (
              <div className="text-slate-500 italic w-[14rem]">
                Email+Password provider is not enabled
              </div>
            )}
          </div>
        </div>
      </div>
    </main>
  );
}

export const action = async ({ request }: ActionFunctionArgs) => {
  return auth.emailPasswordSignUp(request, async ({ error, tokenData }) => {
    if (error) {
      return json({ error: error.message, message: null });
    } else {
      try {
        if (!tokenData) {
          return json({
            error: null,
            message:
              `Email verification required: ` +
              `Follow the link in the verification email to finish registration`,
          });
        }

        await auth.createUser(tokenData);

        return redirect("/");
      } catch (e) {
        let err: any = e instanceof Error ? e.message : String(e);
        try {
          err = JSON.parse(err);
        } catch {}
        return json({
          error: `Error signing up: ${
            err?.error?.message ?? JSON.stringify(err)
          }`,
          message: null,
        });
      }
    }
  });
};

// sveltekit-auth/src/routes/signup/+page.svelte
<script lang="ts">
  import { page } from "$app/stores";
  import Icon from "@iconify/svelte";
  import ResendVerificationEmail from "$lib/components/auth/ResendVerificationEmail.svelte";
  import SignUpForm from "$lib/components/auth/SignUpForm.svelte";
  import { transformSearchParams } from "$lib/utils";

  export let params = transformSearchParams($page.url.searchParams);
  export let data;
  export let form;
</script>

<div class="p-8 min-w-[32rem]">
  <a href={"/"} class="text-slate-600 inline-flex gap-1 items-center mb-2">
    <Icon icon="mdi:keyboard-backspace" />
    Home
  </a>
  <h1 class="text-3xl font-semibold mb-6">Sign up</h1>

  <div class="flex gap-[5rem] w-max">
    <div class="flex flex-col gap-4">
      <h2 class="text-xl font-semibold">Email+Password</h2>
      {#if params.email_verification_error}
        <div
          class="bg-rose-100 text-rose-950 px-4 py-3 rounded-md w-[22rem] flex flex-col items-start"
        >
          {params.email_verification_error}
          {#if params.verification_token}
            <ResendVerificationEmail
              error={form?.error || null}
              message={form?.message || null}
              verificationToken={Array.isArray(params.verification_token)
                ? params.verification_token[0]
                : params.verification_token}
            />
          {/if}
        </div>
      {/if}
      {#if data.providerInfo.emailPassword}
        <SignUpForm error={form?.error} message={form?.message} />
      {:else}
        <div class="text-slate-500 italic w-[14rem]">
          Email+Password provider is not enabled
        </div>
      {/if}
    </div>
  </div>
</div>
