// nextjs-auth/src/app/signin/page.tsx
import Link from "next/link";

import { auth } from "@/edgedb";
import { BackIcon, OAuthIcons } from "@/app/icons";

import { SignInForm } from "@/components/auth";

export default async function SignInPage({
  searchParams,
}: {
  searchParams: { [key: string]: string | string[] | undefined };
}) {
  const providerInfo = await auth.getProvidersInfo();

  return (
    <main className="my-auto p-8 min-w-[32rem]">
      <Link
        href={"/"}
        className="text-slate-600 inline-flex gap-1 items-center mb-2"
      >
        <BackIcon />
        Home
      </Link>
      <h1 className="text-3xl font-semibold mb-6">Sign in</h1>

      <div className="flex gap-[5rem] w-max">
        <div className="flex flex-col gap-4 w-[18rem]">
          <h2 className="text-xl font-semibold">OAuth</h2>

          {searchParams.oauth_error ? (
            <div className="bg-rose-100 text-rose-950 px-4 py-3 rounded-md">
              {searchParams.oauth_error}
            </div>
          ) : null}

          {providerInfo.oauth.length ? (
            providerInfo.oauth.map((provider) => (
              <a
                key={provider.name}
                href={auth.getOAuthUrl(provider.name)}
                className="rounded-lg bg-slate-50 p-3 font-medium shadow-md shrink-0 hover:bg-white hover:scale-[1.03] transition-transform
                flex items-center"
              >
                {OAuthIcons[provider.name]}
                <span className="ml-3">{provider.display_name}</span>
              </a>
            ))
          ) : (
            <div className="text-slate-500 italic w-[14rem]">
              No OAuth providers configured
            </div>
          )}
        </div>

        <div className="flex flex-col gap-4">
          <h2 className="text-xl font-semibold">Email+Password</h2>
          {providerInfo.emailPassword ? (
            <SignInForm />
          ) : (
            <div className="text-slate-500 italic w-[14rem]">
              Email+Password provider is not enabled
            </div>
          )}
        </div>
      </div>
    </main>
  );
}

// sveltekit-auth/src/routes/signin/+page.svelte
<script lang="ts">
  import { page } from "$app/stores";
  import Icon from "@iconify/svelte";
  import { transformSearchParams } from "$lib/utils";
  import SignInForm from "$lib/components/auth/SignInForm.svelte";
  import clientAuth from "$lib/auth.js";

  const providerIcons = {
    "builtin::oauth_apple": "apple",
    "builtin::oauth_azure": "microsoft-azure",
    "builtin::oauth_github": "github",
    "builtin::oauth_google": "google",
  };

  export let params = transformSearchParams($page.url.searchParams);
  export let data;
  export let form;
</script>

<div class="p-8 min-w-[32rem]">
  <a href={"/"} class="text-slate-600 inline-flex gap-1 items-center mb-2">
    <Icon icon="mdi:keyboard-backspace" />
    Home
  </a>
  <h1 class="text-3xl font-semibold mb-6">Sign in</h1>

  <div class="flex gap-[5rem] w-max">
    <div class="flex flex-col gap-4 w-[18rem]">
      <h2 class="text-xl font-semibold">OAuth</h2>
      {#if params.oauth_error}
        <div class="bg-rose-100 text-rose-950 px-4 py-3 rounded-md">
          {params.oauth_error}
        </div>
      {/if}

      {#if data.providers.oauth.length}
        {#each data.providers.oauth as provider (provider.name)}
          <a
            href={clientAuth.getOAuthUrl(provider.name)}
            class="rounded-lg bg-slate-50 p-3 font-medium shadow-md shrink-0 hover:bg-white hover:scale-[1.03] transition-transform
flex items-center"
          >
            <Icon icon={`mdi:${providerIcons[provider.name]}`} />
            <span class="ml-3">{provider.display_name}</span>
          </a>
        {/each}
      {:else}
        <div class="text-slate-500 italic w-[14rem]">
          No OAuth providers configured
        </div>
      {/if}
    </div>

    <div class="flex flex-col gap-4">
      <h2 class="text-xl font-semibold">Email+Password</h2>
      {#if data.providers.emailPassword}
        <SignInForm error={form?.error ?? null} />
      {:else}
        <div class="text-slate-500 italic w-[14rem]">
          Email+Password provider is not enabled
        </div>
      {/if}
    </div>
  </div>
</div>
